### ISSUE TITLE
Please consider to support pnpm.

### ISSUE THREAD

**Issue by ZanMinKian** [legend80s/commit-msg-linter#13]
![image](https://user-images.githubusercontent.com/35495628/145768061-dd9ebe7d-44bd-479c-87bd-9beea505f36a.png)

**Comment by ZanMinKian** [comment]
pnpm is much more popular today. suggestions are follow:
![image](https://user-images.githubusercontent.com/35495628/145768541-32ca6fc6-3e47-4bb2-a407-9369700f0939.png)

**Comment by legend80s** [comment]
OK, we will take it into consideration.

**Comment by legend80s** [comment]
The problem `Error: Cannot find module 'did-you-mean'` reproduced after I install pnpm and copy the commit-msg.js to .git/hooks/commit-msg. But I don't know how to solve it. I need some help because it's my first tour to pnpm 😅.
And I found the `install` script in package.json not executed when run `pnpm add git-commit-msg-linter -D`.

**Comment by legend80s** [comment]
makeshift
```
pnpm install --shamefully-hoist 
```

**Comment by legend80s** [comment]
The module not found problem has be solve in `git-commit-msg-linter@3.3.2` instead of using  the makeshift above 🎉.
