### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by frontlab-ml** [legend80s/commit-msg-linter#3]
I. Currently, I can modify/overwrite the type section and I can define my own. 

  ************* Invalid Git Commit Message **************
  commit message: fix: test
  correct format: <type>(<scope>): <subject> => **_Can I modify commit pattern?_**
  example:        docs: update README => **_This section is hardcoded in hook. Is there any place where I can put README file with my example?_**

II.  
  scope:
    Optional, can be anything specifying place of the commit change.
    For example $location, $browser, $compile, $rootScope, ngHref, ngClick, ngView, etc.
    In App Development, scope can be a page, a module or a component.

  subject:
    A very short description of the change in one line.

**_Can I change the description in these two sections?_**

**Comment by legend80s** [comment]
1. The commit pattern `<type>(<scope>): <subject>` should not be modified because it is guided by Angular.js Git Commit Guidelines and that is what the linter tools exists for.
2. example section will be configured in next release soon.
3. description section will be configured in next release soon too.

**Comment by legend80s** [comment]
New version released. If your requirements are met I will close the issue. @frontlab-ml

**Comment by frontlab-ml** [comment]
@legend80s thanks mate, everything looks good!
